### PR TITLE
fix CI for py3.12 issue

### PR DESCRIPTION
**Pull request by IAlibay**
Please see https://github.com/MDAnalysis/cookiecutter-mdakit/pull/93 for more details.

Also:
 - Bump up versioneer to 0.29 to eventually enable py3.12

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM

**Comment by hmacdope** [comment]
Oh wait RTD, illl fix that.

**Comment by IAlibay** [comment]
@hmacdope I've added the necessary fix here

**Comment by IAlibay** [comment]
I've applied `black` locally and the linter here still complains 🤷🏽 I'm calling it a day on this one.

**Comment by IAlibay** [comment]
@hmacdope I'm leaving it up to you to merge.

**Comment by hmacdope** [comment]
Thanks @IAlibay :)

**Review by hmacdope — APPROVED** [review]

**Comment by xhgchen** [comment]
Thanks @IAlibay! Might be failing because I set up `black` to check for `--line-length 79`. Will try removing that and seeing if it is less strict.

**Pull request merged**
